/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    Authentication: typeof import('./src/components/alerts/authentication.vue')['default']
    CartPage: typeof import('./src/components/apps/ECommerce/CartPage.vue')['default']
    CommonTable: typeof import('./src/components/apps/Tables/CommonTable.vue')['default']
    Dashboard: typeof import('./src/components/apps/Dashboard.vue')['default']
    ECommerce: typeof import('./src/components/apps/ECommerce.vue')['default']
    FilterTable: typeof import('./src/components/apps/Tables/filterTable.vue')['default']
    Items: typeof import('./src/components/apps/ECommerce.vue')['default']
    Login: typeof import('./src/components/authentication/Login.vue')['default']
    OrdersPage: typeof import('./src/components/apps/ECommerce/OrdersPage.vue')['default']
    OrderSuccess: typeof import('./src/components/apps/ECommerce/OrderSuccess.vue')['default']
    PaymentPage: typeof import('./src/components/apps/ECommerce/PaymentPage.vue')['default']
    ProductCard: typeof import('./src/components/apps/ECommerce/ProductList.vue')['default']
    ProductDetails: typeof import('./src/components/apps/ECommerce/ProductDetails.vue')['default']
    ProductList: typeof import('./src/components/apps/ECommerce/ProductList.vue')['default']
    ProductPage: typeof import('./src/components/apps/ECommerce/ProductPage.vue')['default']
    ProductTable: typeof import('./src/components/apps/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/authentication/Signup.vue')['default']
    TodoList: typeof import('./src/components/apps/TodoList.vue')['default']
  }
}
